### ISSUE TITLE
Mongo collections don't match schemas

### ISSUE THREAD

**Issue by fboucquez** [symbol/catbuffer-schemas#2] opened 2021-05-23 12:57 UTC
Mongo collections are pretty close to the schemas but not enough. There are several discrepancies. Some of them are:

- Missing meta objects.
- Missing "wrapper" objects (like {meta, block} ones)
- Nested/flat fields. Example:

Stored flat:

![image](https://user-images.githubusercontent.com/5390558/119260726-6fd50d00-bbaa-11eb-88b5-1ac0b44350cf.png)

But the block schema uses a nested `generationHashProof` field 

https://github.com/nemtech/catbuffer-schemas/blob/main/schemas/block.cats#L34

There are several issues like these ones. 

I know catbuffer schemas are designed for binary serialization but it would be nice if we can generate different models based on it.  I would like to generate tyepscript/mongo, openapi ([question](https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1617295088396700?thread_ts=1617285092.390400&cid=C015AEQ9ZL2)), graphql models based on the schemas but atm it's not possible without hacking the generators too much.

Currently, open [API schemas](https://github.com/nemtech/symbol-openapi/blob/main/spec/core/block/schemas/BlockDTO.yml#L28) and [catapult-rest "codecs"](https://github.com/nemtech/catapult-rest/blob/main/catapult-sdk/src/modelBinary/blockHeaderCodec.js#L27) are manually written based on how the objects are stored, not how they are represented in the catbuffer schemas

**Comment by gimer** [comment] 2021-05-24 16:19
1. catbuffer was never intended to describe db field / layout (but technically could be
2. if anything should be changed it's probably mongodb collection, so I renamed the issue.

**Comment by fboucquez** [comment] 2021-05-24 17:33
Yes, catbuffer was intended for serialization. When you flat the data into a binary stream, the result is the same. 

I'm trying to see if we can extend the schemas to reflect the nature of the stored data (or the other way around).

Patching the collections would have a wider impact, from broker, mongo, indexes, open API, rest API, sdks, and clients. Plus the data migration from one structure to another.

If this is not doable/practical we may need to keep manually creating/mantaining the models from the stored data, at least the ones that don't match. 

Block schema is just one example, there are others.

**Comment by Jaguar0625** [comment] 2021-05-24 19:03
> Missing meta objects

many of these are computed and make no sense from a serialization point of view. i'm not sure why it would be advisable to include them in a serialization description.

**Comment by Jaguar0625** [comment] 2021-05-24 19:04
> Patching the collections would have a wider impact, from broker, mongo, indexes, open API, rest API, sdks, and clients. Plus the data migration from one structure to another.

obviously, it is a far less disruptive change to change REST/mongo to match these schemas than to change the binary format, which would require a hardfork.

**Comment by fboucquez** [comment] 2021-05-24 20:51
>many of these are computed and make no sense from a serialization point of view. i'm not sure why it would be advisable to include them in a serialization description.

Just to be complete so the schemas could be used to load the whole collection. But if it doesn't make sense, we can maintain meta objects manually 

> obviously, it is a far less disruptive change to change REST/mongo to match these schemas than to change the binary format, which would require a hardfork.

Not necessary, the schema structure can change, but the serialized binary could be the same. 

The block:

Current catbuffer schema (nested):
````
{
    ...
    "generationHashProof": {
        gamma: 'A'
        verificationHash:'B"
        scalar: 'C'
     }
.....
} 
````
Current mongo data (flat):

````
{
    ...
        proofGamma: 'A'
        proofVerificationHash:'B"
        proofScalar: 'C'
.....
} 
````
Both serialized objects are `...ABC...`. 

The theory goes, if we change the catbuffer schema to be flat in that area, the schema can be used to map the mongo objects and/or generator open API without affecting the serialization.

**Comment by gimer** [comment] 2021-08-05 12:44
every document in mongo costs (but that is a minor thing, and I don't really care)

regarding `generationHashProof`, yes, I agree mongo schema _should_ be changed to match both catbuffer schema (and actual Block layout)

the problem is this though: we don't really have way to do rocksdb migration and in general: migration handling in mongo is pretty much non-existing.
(yes we could enforce full sync, but that is less than optimal...)

**Comment by fboucquez** [comment] 2021-08-05 13:54
Yes, it's fine, I agree the migration will be pretty costly. This issue would probably not be fixed in the existing rest/catapult but it's good to consider for the next implementation of a catapult/rest/database. 

What I tried to prove is if can use the catbuffer schemas and generators to generate the 1) Mongo/DB ORM objects and 2) The open API schemas. I failed because of the differences between the existing mongo, open apis, and the catbuffer schemas. The generators were getting too hacky too soon before I gave up and raised this issue.

**Comment by segfaultxavi** [comment] 2021-09-01 16:29
For my own understanding:
The problem is that the structures used in binary serialization and the DB are different in many places. Some differences are:
- Missing meta objects (these is derived data which can be recalculated)
- Missing wrapper objects
- Nested/Flat structures

Right now neither side can be easily changed (a serialization change requires a hard fork, a DB change require all nodes to migrate their multigigabyte DBs).

Is this correct?

I think fixing this would be a HUGE advantage (think autogenerated OpenAPI) so it's worth investigate a big further.

What was the reason for initially using different layouts?
Would adding metadata (comments) or naming conventions to the schemas help?

**Comment by Jaguar0625** [comment] 2021-09-01 17:01
Is there a list of **all** the discrepancies? In this thread I only see `generationHashProof` being discussed?

As far as metadata, since catbuffer was initially intended to be a protobuf like description of binary content, it's not surprising those aren't defined. While it's a bit of an abuse, there's nothing preventing someone defining those objects in CATS files.

**Comment by segfaultxavi** [comment] 2021-09-01 17:46
> As far as metadata, since catbuffer was initially intended to be a protobuf like description of binary content, it's not surprising those aren't defined. While it's a bit of an abuse, there's nothing preventing someone defining those objects in CATS files.

Sorry I wasn't clear. I meant that we could add "metadata" to the cats files to help in the conversion between binary and DB formats. Something like `#<group` and `#>group` comment tags to indicate that some fields should be grouped (I have no idea what I'm talking about, just brainstorming).

> Is there a list of all the discrepancies? 

Since @fboucquez did the initial research maybe he can explain where he got in the process? Or provide some list, even if incomplete?

**Comment by Jaguar0625** [comment] 2021-12-22 21:34
If we were to do anything with this, we'd probably need to do it on server side (i.e. mongo upgrade and/or replacement). So, closing since it doesn't belong in this (catbuffer-schemas) repository.

**Closed by Jaguar0625** 2021-12-22 21:34 UTC
